[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["stormcow <janek237krokodyl@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
mypy = "^1.5.1"
black = "^23.9.1"
fastapi = "^0.103.1"
uvicorn = "^0.23.2"
flake8 = "^6.1.0"
pydantic = "^2.4.2"
httpio = "^0.3.0"
sqlalchemy = "^2.0.21"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
strict = true

[tool.flake8]
max-line-length = 88